#!/usr/bin/env python3
"""
Generate template for daily notes
"""
import argparse
import os
import sys

from datetime import datetime, timedelta
from string import Template

t = """# $start

## Goals
- .

## Hours
$hours_output

## Reading
- .
"""


def main():
    template = Template(t)
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', dest='verbose', action='store_true')
    args = parser.parse_args()
    start = datetime.now().replace(hour=8, minute=0, second=0, microsecond=0)
    blocks = [105,15,15,105,60,60,60,60,60,60,60]
    hours = []
    h_t = "{:%I:%M} - {:%I:%M}"
    block_start = start
    for block in blocks:
        block_end = block_start + timedelta(minutes=block)
        hours.append(h_t.format(block_start, block_end))
        block_start = block_end
    hours_output = '\n- .\n\n'.join(hours)
    # output = f"# {start:%Y-%m-%d}\n\n## Goals\n- .\n\n## Hours\n{hours_output}"
    output = template.substitute({"start": f"{start:%Y-%m-%d}", "hours_output": hours_output})
    if args.verbose:
        print(output)
    else:
        os.system(f'echo "{output}" | pbcopy')

    return 0

sys.exit(main())
