" Expand tab
set expandtab
set tabstop=4
set shiftwidth=4


" add yaml stuffs
au! BufNewFile,BufReadPost *.{yaml,yml} set filetype=yaml foldmethod=indent
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab


let g:ctrlp_cache_dir = $HOME . '/.cache/ctrlp'
if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif

" Enable syntax
syntax on

" Enable use of FZF
" set rtp+=/usr/local/opt/fzf
