# basics
export VISUAL=vim
export EDITOR=$VISUAL

export PATH=~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin
alias notify='/Applications/terminal-notifier_1.4.2/terminal-notifier.app/Contents/MacOS/terminal-notifier'
alias sane='echo -e "\\033c";tput is2; \'·

# Ruby
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# virtualenv
export WORKON_HOME=~/Code/venv
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
source /usr/local/bin/virtualenvwrapper.sh
export VIRTUAL_ENV_DISABLE_PROMPT=1

# golang
export GOPATH=~/Code/go
PATH=${PATH}:${GOPATH}/bin


# AWS
function awsenv() {
    export AWS_DEFAULT_PROFILE=${1}
    export AWS_PROFILE=${1}
    AWS_BIN=$(which aws)
    if [[ $AWS_BIN ]]; then
        complete -C "$(dirname ${AWS_BIN})/aws_completer" aws
    fi
}

# bash-completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    GIT_PS1_SHOWDIRTYSTATE=1
    source $(brew --prefix)/etc/bash_completion
    source ${BASH_COMPLETION_DIR}/git-prompt.sh
    # display the current branch in the prompt
    RED='\[\e[031m\]'
    END_COLOR='\[\e[0m\]'
    export PS1="${RED}${AWS_PROFILE:="-"}\$(__git_ps1 ' (%s)') ${END_COLOR}👻  "
else
    printf "No bash completion located at %s" $(brew --prefix)
fi


# pip bash completion start
_pip_completion()
{
    COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   PIP_AUTO_COMPLETE=1 $1 ) )
}
complete -o default -F _pip_completion pip
# pip bash completion end

# Source highlight with less
export LESSOPEN="| src-hilite-lesspipe.sh %s"
export LESS=' -R '

# Set the title of the terminal tab
function title {
    echo -ne "\033]0;"$*"\007"
}


[ -f ~/.bashrc.work ] && source ~/.bashrc.work
