# basics
export VISUAL=nvim
export EDITOR=$VISUAL

# Set unlimited history
HISTSIZE=
HISTFILESIZE=

export PATH=~/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin:/Library/TeX/texbin
export MANPATH=${MANPATH}:$HOMEBREW_PREFIX/opt/coreutils/libexec/gnuman
alias notify='/Applications/terminal-notifier_1.4.2/terminal-notifier.app/Contents/MacOS/terminal-notifier'
alias sane='echo -e "\\033c";tput is2; \'
alias allremotes='git branch -r | grep -v "\-\>" | while read remote; do git branch --track "${remote#origin/}" "$remote"; done'


# Ruby
# export PATH="$HOME/.rbenv/bin:$PATH"
# eval "$(rbenv init -)"

# virtualenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# golang
export GOPATH=~/Code/go
PATH=${PATH}:${GOPATH}/bin


# AWS
function awsenv() {
    export AWS_DEFAULT_PROFILE=${1}
    export AWS_PROFILE=${1}
    AWS_BIN=$(which aws)
    if [[ $AWS_BIN ]]; then
        complete -C "$(dirname ${AWS_BIN})/aws_completer" aws
    fi
}

# Set the title of the terminal tab
function title {
    echo -ne "\033]0;"$*"\007"
}

function json_to_yaml {
    python3 -c 'import sys, yaml, json; yaml.safe_dump(json.load(sys.stdin), sys.stdout, default_flow_style=False)'
}

# node version management
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

[ -f ~/.bashrc.work ] && source ~/.bashrc.work

# https://github.com/nvm-sh/nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# https://github.com/junegunn/fzf#respecting-gitignore
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='fd --type d'

# https://starship.rs/guide/#%F0%9F%9A%80-installation
eval "$(starship init bash)"

# Setup PARA aliases
alias i='cd ~/Inbox'
alias p='cd ~/Projects'
alias a='cd ~/Areas'
alias r='cd ~/Resources'
