# Source the interactive config file since in iTerm, each new tab is a login
# shell.
if [ -f ~/.bashrc ]; then
       source ~/.bashrc
fi

export PATH="$HOME/.cargo/bin:$PATH"

source /Users/aso/Library/Preferences/org.dystroy.broot/launcher/bash/br
