# Source the interactive config file since in iTerm, each new tab is a login
# shell.
if [ -f ~/.bashrc ]; then
       source ~/.bashrc
fi

export PATH="$HOME/.cargo/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
